### ISSUE TITLE
[Demo] Add Cluster Example to EMA-Studio

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/ClusterFiddle#2]
Hi @sschneiders,

since you mean that the WASM code is very slow and/or you have problems translating the C++ code to WASM, you can also use the native version.
Just create a batch file to compile your ClusterFiddle to C++ and to a DLL, and create a batch file to cluster your image with the generated DLL.

If you did this, you can ask @0xJMR if he also integrates your project next to the Autopilot project into the IDE in EmbeddedMontiArc studio. (@0xJMR just add two additional buttons for compiling in the IDE and one for running in the HTML ClusterFiddle site).

I would like to show the cluster fiddle since it uses the external library for fast Matrix operations; so that Prof. Rumpe can see that you have an advantage using our language instead of Java (Java does not support SIMD and GPU).

**Anyway it is not bad to integrate it in EmbeddedMontiArcStudio**, as we will distribute this version to others, and so your example is also there.

**Comment by vonwenckstern** [comment]
https://github.com/EmbeddedMontiArc/EmbeddedMontiArcStudio

**Comment by vonwenckstern** [comment]
@sschneiders, @0xJMR The best way is to make two subfolders in the `script` folder:
* `autopilot`: all scripts for compiling, simulating the Autopilot as well as creating SVG visualization and reporting for the Autopilot model
* `clustering`: all scripts for compiling, image-clustering (running the html-page) as well as creating SVG visualization and reporting for the clustering model
* the `ide.bat` file can be directly in the `scripts` folder (this way it is clear what batch file the user should execute -- since there is now only one directly in the `scripts` folder left -- rest moved to the subfolders)

**Comment by 0xJMR** [comment]
As far as I am aware, this issue should be solved.
